### ISSUE TITLE
Discuss the problems of decalring things in global scope

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/js-principles-scope-readme#1]
referencing this issue: https://github.com/learn-co-curriculum/js-principles-scope-lab/issues/2

The lab has students play with it, but we never explain how to create global variables and such in this README

**Comment by gj** [comment]
@jmburges Good point. I was purposefully avoiding even mentioning global variables, but I suppose it's valuable information to have for debugging purposes. Maybe they'll mistakenly leave off a `const` or `let`, etc.

Will introduce how to declare them with a ***strong*** caveat to never, ever use globals.

**Comment by jmburges** [comment]
👍

**Comment by gj** [comment]
Issue link is dead, but I added a section on global vars
