### ISSUE TITLE
Show off the re-declaration error for let

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/js-principles-scope-readme#2]
This issue: https://github.com/learn-co-curriculum/js-principles-scope-lab/issues/5

We need to show them the error that happens when you re-declare `let` in different scopes

**Comment by gj** [comment]
Issue link is dead @jmburges.

Not sure what you mean by "the error that happens when you re-declare `let` in different scopes." As long as they're in different scopes, multiple declarations with `let` should be fine.
